# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\thwan\Desktop\DRT\Gui_revision\py-DRTtools\GUI\gui_v5\gui_layout_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plot_panel = QtWidgets.QGraphicsView(self.centralwidget)
        self.plot_panel.setGeometry(QtCore.QRect(340, 50, 741, 621))
        self.plot_panel.setObjectName("plot_panel")
        self.show_frame = QtWidgets.QFrame(self.centralwidget)
        self.show_frame.setGeometry(QtCore.QRect(340, 20, 741, 31))
        self.show_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.show_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.show_frame.setObjectName("show_frame")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.show_frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 741, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.show_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.show_layout.setContentsMargins(0, 0, 0, 0)
        self.show_layout.setSpacing(0)
        self.show_layout.setObjectName("show_layout")
        self.show_EIS = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_EIS.setFont(font)
        self.show_EIS.setAutoDefault(False)
        self.show_EIS.setObjectName("show_EIS")
        self.show_layout.addWidget(self.show_EIS)
        self.show_mag = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_mag.setFont(font)
        self.show_mag.setObjectName("show_mag")
        self.show_layout.addWidget(self.show_mag)
        self.show_phase = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_phase.setFont(font)
        self.show_phase.setObjectName("show_phase")
        self.show_layout.addWidget(self.show_phase)
        self.show_re = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_re.setFont(font)
        self.show_re.setObjectName("show_re")
        self.show_layout.addWidget(self.show_re)
        self.show_im = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_im.setFont(font)
        self.show_im.setObjectName("show_im")
        self.show_layout.addWidget(self.show_im)
        self.show_re_res = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_re_res.setFont(font)
        self.show_re_res.setObjectName("show_re_res")
        self.show_layout.addWidget(self.show_re_res)
        self.show_im_res = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_im_res.setFont(font)
        self.show_im_res.setObjectName("show_im_res")
        self.show_layout.addWidget(self.show_im_res)
        self.show_DRT = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_DRT.setFont(font)
        self.show_DRT.setObjectName("show_DRT")
        self.show_layout.addWidget(self.show_DRT)
        self.show_score = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_score.setFont(font)
        self.show_score.setObjectName("show_score")
        self.show_layout.addWidget(self.show_score)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 311, 291))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_9 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(10, 15, 291, 270))
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.general_layout = QtWidgets.QFormLayout(self.formLayoutWidget_9)
        self.general_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.general_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.general_layout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.general_layout.setLabelAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.general_layout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.general_layout.setContentsMargins(0, 0, 0, 0)
        self.general_layout.setHorizontalSpacing(10)
        self.general_layout.setVerticalSpacing(15)
        self.general_layout.setObjectName("general_layout")
        self.import_label = QtWidgets.QLabel(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.import_label.setFont(font)
        self.import_label.setAlignment(QtCore.Qt.AlignCenter)
        self.import_label.setObjectName("import_label")
        self.general_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.import_label)
        self.import_button = QtWidgets.QPushButton(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.import_button.setFont(font)
        self.import_button.setObjectName("import_button")
        self.general_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.import_button)
        self.discre_choice = QtWidgets.QComboBox(self.formLayoutWidget_9)
        self.discre_choice.setMinimumSize(QtCore.QSize(106, 0))
        self.discre_choice.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.discre_choice.setFont(font)
        self.discre_choice.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.discre_choice.setObjectName("discre_choice")
        self.discre_choice.addItem("")
        self.discre_choice.addItem("")
        self.discre_choice.addItem("")
        self.discre_choice.addItem("")
        self.discre_choice.addItem("")
        self.discre_choice.addItem("")
        self.discre_choice.addItem("")
        self.discre_choice.addItem("")
        self.general_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.discre_choice)
        self.data_used_label = QtWidgets.QLabel(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.data_used_label.setFont(font)
        self.data_used_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_used_label.setObjectName("data_used_label")
        self.general_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.data_used_label)
        self.data_used_choice = QtWidgets.QComboBox(self.formLayoutWidget_9)
        self.data_used_choice.setMinimumSize(QtCore.QSize(106, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_used_choice.setFont(font)
        self.data_used_choice.setStyleSheet("QComboBox QAbstractItemView {min-width: 150px;}")
        self.data_used_choice.setEditable(False)
        self.data_used_choice.setMaxVisibleItems(10)
        self.data_used_choice.setMaxCount(2147483647)
        self.data_used_choice.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.data_used_choice.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.data_used_choice.setMinimumContentsLength(10)
        self.data_used_choice.setIconSize(QtCore.QSize(25, 16))
        self.data_used_choice.setFrame(True)
        self.data_used_choice.setObjectName("data_used_choice")
        self.data_used_choice.addItem("")
        self.data_used_choice.addItem("")
        self.data_used_choice.addItem("")
        self.general_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.data_used_choice)
        self.induct_label = QtWidgets.QLabel(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.induct_label.setFont(font)
        self.induct_label.setAlignment(QtCore.Qt.AlignCenter)
        self.induct_label.setWordWrap(True)
        self.induct_label.setObjectName("induct_label")
        self.general_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.induct_label)
        self.induct_choice = QtWidgets.QComboBox(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.induct_choice.setFont(font)
        self.induct_choice.setStyleSheet("QComboBox QAbstractItemView {min-width: 150px;}")
        self.induct_choice.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.induct_choice.setObjectName("induct_choice")
        self.induct_choice.addItem("")
        self.induct_choice.addItem("")
        self.induct_choice.addItem("")
        self.general_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.induct_choice)
        self.der_label = QtWidgets.QLabel(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.der_label.setFont(font)
        self.der_label.setAlignment(QtCore.Qt.AlignCenter)
        self.der_label.setWordWrap(False)
        self.der_label.setObjectName("der_label")
        self.general_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.der_label)
        self.der_choice = QtWidgets.QComboBox(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.der_choice.setFont(font)
        self.der_choice.setObjectName("der_choice")
        self.der_choice.addItem("")
        self.der_choice.addItem("")
        self.general_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.der_choice)
        self.reg_para_label = QtWidgets.QLabel(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.reg_para_label.setFont(font)
        self.reg_para_label.setObjectName("reg_para_label")
        self.general_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.reg_para_label)
        self.reg_para_entry = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reg_para_entry.setFont(font)
        self.reg_para_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.reg_para_entry.setObjectName("reg_para_entry")
        self.general_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.reg_para_entry)
        self.sample_no_label = QtWidgets.QLabel(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sample_no_label.setFont(font)
        self.sample_no_label.setObjectName("sample_no_label")
        self.general_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.sample_no_label)
        self.sample_no_entry = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sample_no_entry.setFont(font)
        self.sample_no_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.sample_no_entry.setObjectName("sample_no_entry")
        self.general_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.sample_no_entry)
        self.discre_label = QtWidgets.QLabel(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.discre_label.setFont(font)
        self.discre_label.setWordWrap(False)
        self.discre_label.setIndent(0)
        self.discre_label.setObjectName("discre_label")
        self.general_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.discre_label)
        self.RBF_frame = QtWidgets.QGroupBox(self.centralwidget)
        self.RBF_frame.setGeometry(QtCore.QRect(20, 310, 311, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RBF_frame.setFont(font)
        self.RBF_frame.setMouseTracking(False)
        self.RBF_frame.setAutoFillBackground(True)
        self.RBF_frame.setTitle("Options for RBF")
        self.RBF_frame.setObjectName("RBF_frame")
        self.formLayoutWidget_10 = QtWidgets.QWidget(self.RBF_frame)
        self.formLayoutWidget_10.setGeometry(QtCore.QRect(10, 25, 291, 71))
        self.formLayoutWidget_10.setObjectName("formLayoutWidget_10")
        self.RBF_option_layout = QtWidgets.QFormLayout(self.formLayoutWidget_10)
        self.RBF_option_layout.setContentsMargins(0, 0, 0, 0)
        self.RBF_option_layout.setHorizontalSpacing(47)
        self.RBF_option_layout.setVerticalSpacing(14)
        self.RBF_option_layout.setObjectName("RBF_option_layout")
        self.shape_control_label = QtWidgets.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shape_control_label.setFont(font)
        self.shape_control_label.setObjectName("shape_control_label")
        self.RBF_option_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.shape_control_label)
        self.shape_control_choice = QtWidgets.QComboBox(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shape_control_choice.setFont(font)
        self.shape_control_choice.setStyleSheet("QComboBox QAbstractItemView {min-width: 150px;}")
        self.shape_control_choice.setObjectName("shape_control_choice")
        self.shape_control_choice.addItem("")
        self.shape_control_choice.addItem("")
        self.RBF_option_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.shape_control_choice)
        self.FWHM_control_label = QtWidgets.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FWHM_control_label.setFont(font)
        self.FWHM_control_label.setObjectName("FWHM_control_label")
        self.RBF_option_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.FWHM_control_label)
        self.FWHM_entry = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FWHM_entry.setFont(font)
        self.FWHM_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.FWHM_entry.setObjectName("FWHM_entry")
        self.RBF_option_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.FWHM_entry)
        self.run_frame = QtWidgets.QGroupBox(self.centralwidget)
        self.run_frame.setGeometry(QtCore.QRect(20, 410, 311, 131))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.run_frame.setFont(font)
        self.run_frame.setAutoFillBackground(True)
        self.run_frame.setObjectName("run_frame")
        self.formLayoutWidget_11 = QtWidgets.QWidget(self.run_frame)
        self.formLayoutWidget_11.setGeometry(QtCore.QRect(10, 20, 291, 108))
        self.formLayoutWidget_11.setObjectName("formLayoutWidget_11")
        self.run_layout = QtWidgets.QFormLayout(self.formLayoutWidget_11)
        self.run_layout.setContentsMargins(0, 0, 0, 0)
        self.run_layout.setHorizontalSpacing(53)
        self.run_layout.setVerticalSpacing(14)
        self.run_layout.setObjectName("run_layout")
        self.simple_run_label = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.simple_run_label.setFont(font)
        self.simple_run_label.setObjectName("simple_run_label")
        self.run_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.simple_run_label)
        self.simple_run_button = QtWidgets.QPushButton(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.simple_run_button.setFont(font)
        self.simple_run_button.setObjectName("simple_run_button")
        self.run_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.simple_run_button)
        self.bayes_label = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bayes_label.setFont(font)
        self.bayes_label.setObjectName("bayes_label")
        self.run_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bayes_label)
        self.bayesian_button = QtWidgets.QPushButton(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bayesian_button.setFont(font)
        self.bayesian_button.setObjectName("bayesian_button")
        self.run_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bayesian_button)
        self.HT_label = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.HT_label.setFont(font)
        self.HT_label.setObjectName("HT_label")
        self.run_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.HT_label)
        self.HT_button = QtWidgets.QPushButton(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.HT_button.setFont(font)
        self.HT_button.setObjectName("HT_button")
        self.run_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.HT_button)
        self.export_frame = QtWidgets.QGroupBox(self.centralwidget)
        self.export_frame.setGeometry(QtCore.QRect(20, 550, 311, 131))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.export_frame.setFont(font)
        self.export_frame.setAutoFillBackground(True)
        self.export_frame.setObjectName("export_frame")
        self.formLayoutWidget_12 = QtWidgets.QWidget(self.export_frame)
        self.formLayoutWidget_12.setGeometry(QtCore.QRect(10, 21, 291, 106))
        self.formLayoutWidget_12.setObjectName("formLayoutWidget_12")
        self.export_layout = QtWidgets.QFormLayout(self.formLayoutWidget_12)
        self.export_layout.setContentsMargins(0, 0, 0, 0)
        self.export_layout.setHorizontalSpacing(68)
        self.export_layout.setVerticalSpacing(13)
        self.export_layout.setObjectName("export_layout")
        self.export_DRT_button = QtWidgets.QPushButton(self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.export_DRT_button.setFont(font)
        self.export_DRT_button.setObjectName("export_DRT_button")
        self.export_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.export_DRT_button)
        self.export_EIS_label = QtWidgets.QLabel(self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.export_EIS_label.setFont(font)
        self.export_EIS_label.setObjectName("export_EIS_label")
        self.export_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.export_EIS_label)
        self.export_EIS_button = QtWidgets.QPushButton(self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.export_EIS_button.setFont(font)
        self.export_EIS_button.setObjectName("export_EIS_button")
        self.export_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.export_EIS_button)
        self.export_fig_label = QtWidgets.QLabel(self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.export_fig_label.setFont(font)
        self.export_fig_label.setObjectName("export_fig_label")
        self.export_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.export_fig_label)
        self.export_fig_button = QtWidgets.QPushButton(self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.export_fig_button.setFont(font)
        self.export_fig_button.setObjectName("export_fig_button")
        self.export_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.export_fig_button)
        self.export_DRT_label = QtWidgets.QLabel(self.formLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.export_DRT_label.setFont(font)
        self.export_DRT_label.setObjectName("export_DRT_label")
        self.export_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.export_DRT_label)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.discre_choice.setCurrentIndex(0)
        self.data_used_choice.setCurrentIndex(0)
        self.der_choice.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyDRTtools"))
        self.show_EIS.setText(_translate("MainWindow", "EIS Data"))
        self.show_mag.setText(_translate("MainWindow", "Magnitude"))
        self.show_phase.setText(_translate("MainWindow", "Phase"))
        self.show_re.setText(_translate("MainWindow", "Re Part"))
        self.show_im.setText(_translate("MainWindow", "Im Part"))
        self.show_re_res.setText(_translate("MainWindow", "Re Residual"))
        self.show_im_res.setText(_translate("MainWindow", "Im Residual"))
        self.show_DRT.setText(_translate("MainWindow", "DRT"))
        self.show_score.setText(_translate("MainWindow", "EIS Score"))
        self.groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.import_label.setText(_translate("MainWindow", "Import Data"))
        self.import_button.setText(_translate("MainWindow", "Import"))
        self.discre_choice.setItemText(0, _translate("MainWindow", "Gaussian"))
        self.discre_choice.setItemText(1, _translate("MainWindow", "C2 Matern"))
        self.discre_choice.setItemText(2, _translate("MainWindow", "C4 Matern"))
        self.discre_choice.setItemText(3, _translate("MainWindow", "C6 Matern"))
        self.discre_choice.setItemText(4, _translate("MainWindow", "Inverse Quadratic"))
        self.discre_choice.setItemText(5, _translate("MainWindow", "Inverse Quadric"))
        self.discre_choice.setItemText(6, _translate("MainWindow", "Cauchy"))
        self.discre_choice.setItemText(7, _translate("MainWindow", "Piecewise Linear"))
        self.data_used_label.setText(_translate("MainWindow", "Data Used"))
        self.data_used_choice.setItemText(0, _translate("MainWindow", "Combined Re-Im Data"))
        self.data_used_choice.setItemText(1, _translate("MainWindow", "Re Data"))
        self.data_used_choice.setItemText(2, _translate("MainWindow", "Im Data"))
        self.induct_label.setText(_translate("MainWindow", "Inductance Included"))
        self.induct_choice.setItemText(0, _translate("MainWindow", "Fitting w/o Inductance"))
        self.induct_choice.setItemText(1, _translate("MainWindow", "Fitting with Inductance"))
        self.induct_choice.setItemText(2, _translate("MainWindow", "Discard Inductive Data"))
        self.der_label.setText(_translate("MainWindow", "Regularization Derivative"))
        self.der_choice.setItemText(0, _translate("MainWindow", "1st order"))
        self.der_choice.setItemText(1, _translate("MainWindow", "2nd order"))
        self.reg_para_label.setText(_translate("MainWindow", "Regularization Parameter"))
        self.reg_para_entry.setText(_translate("MainWindow", "1E-3"))
        self.sample_no_label.setText(_translate("MainWindow", "Number of Samples"))
        self.sample_no_entry.setText(_translate("MainWindow", "2000"))
        self.discre_label.setText(_translate("MainWindow", "Method of Discretization"))
        self.shape_control_label.setText(_translate("MainWindow", "RBF Shape Control"))
        self.shape_control_choice.setItemText(0, _translate("MainWindow", "FWHM Coefficient"))
        self.shape_control_choice.setItemText(1, _translate("MainWindow", "Shape Factor"))
        self.FWHM_control_label.setText(_translate("MainWindow", "FWHM Control"))
        self.FWHM_entry.setText(_translate("MainWindow", "0.5"))
        self.run_frame.setTitle(_translate("MainWindow", "Run"))
        self.simple_run_label.setText(_translate("MainWindow", "Simple Run"))
        self.simple_run_button.setText(_translate("MainWindow", "Run"))
        self.bayes_label.setText(_translate("MainWindow", "Bayesian Run"))
        self.bayesian_button.setText(_translate("MainWindow", "Run"))
        self.HT_label.setText(_translate("MainWindow", "Hilbert Transform"))
        self.HT_button.setText(_translate("MainWindow", "Run"))
        self.export_frame.setTitle(_translate("MainWindow", "Export Result"))
        self.export_DRT_button.setText(_translate("MainWindow", "Export"))
        self.export_EIS_label.setText(_translate("MainWindow", "EIS Regression"))
        self.export_EIS_button.setText(_translate("MainWindow", "Export"))
        self.export_fig_label.setText(_translate("MainWindow", "Figure"))
        self.export_fig_button.setText(_translate("MainWindow", "Save"))
        self.export_DRT_label.setText(_translate("MainWindow", "DRT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

